# Generated by Django 4.2.6 on 2023-11-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appActor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='anio_debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='actor',
            name='edad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='actor',
            name='premios',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
