# Generated by Django 4.2.6 on 2023-11-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appActor', '0002_alter_actor_anio_debut_alter_actor_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='anio_debut',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
