# Generated by Django 4.2.6 on 2023-11-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appActor', '0003_alter_actor_anio_debut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='anio_debut',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='actor',
            name='edad',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='actor',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('No Aplica', 'Prefiero no decirlo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='actor',
            name='nacionalidad',
            field=models.CharField(choices=[('Estadounidense', 'Estadounidense'), ('Británico', 'Británico'), ('Canadiense', 'Canadiense'), ('Chileno', 'Chileno'), ('Peruano', 'Peruano'), ('Otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='actor',
            name='premios',
            field=models.PositiveIntegerField(default=''),
        ),
    ]
