# Generated by Django 4.2.6 on 2023-11-15 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appActor', '0003_alter_actor_anio_debut'),
        ('appDirector', '0003_alter_director_cantidad_peliculas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('minutos_duracion', models.PositiveIntegerField(default=0)),
                ('genero', models.CharField(max_length=30)),
                ('fecha_de_estreno', models.DateField()),
                ('presupuesto', models.PositiveIntegerField(default=0)),
                ('recaudacion', models.PositiveIntegerField(default=0)),
                ('clave_foranea_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appActor.actor')),
                ('clave_foranea_director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDirector.director')),
            ],
        ),
    ]
