# Generated by Django 4.2.6 on 2023-11-16 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPelicula', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='clave_foranea_actor',
            new_name='actor_protagonista',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='clave_foranea_director',
            new_name='director',
        ),
    ]
