# Generated by Django 4.2.6 on 2023-11-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPelicula', '0004_alter_pelicula_fecha_de_estreno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='fecha_de_estreno',
            field=models.CharField(default='dd/mm/aaaa', max_length=10),
        ),
    ]
