# Generated by Django 4.2.6 on 2023-11-08 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDirector', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='cantPelis',
            new_name='cantidad_peliculas',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='edadD',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='generoD',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='nacD',
            new_name='nacionalidad',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='nombreD',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='premiosD',
            new_name='premios',
        ),
    ]
