# Generated by Django 4.2.6 on 2023-11-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDirector', '0003_alter_director_cantidad_peliculas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='cantidad_peliculas',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='director',
            name='edad',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='director',
            name='nacionalidad',
            field=models.CharField(choices=[('Estadounidense', 'Estadounidense'), ('Británico', 'Británico'), ('Canadiense', 'Canadiense'), ('Chileno', 'Chileno'), ('Peruano', 'Peruano'), ('Otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='director',
            name='premios',
            field=models.PositiveIntegerField(default=''),
        ),
    ]
